#!/usr/local/bin/perl

#################################################################################################################
# Description: A perl script that automatically downloads pdb files from Protein Data Bank (rcsb.org)			#
# Author: 	   Isidro C. Medina Jr.																				#
# Date: 	   2013																								#
#################################################################################################################

#use Switch;

#print "\nWelcome to the intrinsic disorder prediction tool!\n\n What would you like to do? ";
#print "\n  [1] Identify pdb structures resolved by both X-Ray and NMR.";
#print "\n  [2] Download X-Ray and NMR structures from the Protein Data Bank.";
#print "\n\n  Press q if you want to quit.";

#print "\n\nSelect: ";
#$choice = <STDIN>;  chomp($choice);

#switch ($choice) {
#  case '1' { &open_expMethods  ; }						# Open a list of pdb files resolved by diff exp methods 
#  case '2' { print "\nDownloading pdb files..."; &get_web_pdb;  } # Get the pdb file from Protein Data Bank and write it to an external file
#} print "\n\nThank you for using this tool!\n";

sub open_expMethods {
# source: http://www.pdb.org/pdb/statistics/clusterExpMethods.do
  open (PDBMETH, 'clusterExpMethods.csv');	# Open csv file that contains a list of pdb files resolved by x-ray, nmr & EM-cryo expt 
  @expmethd_input = <PDBMETH>;	close (PDBMETH);
  $expmethd_len = @expmethd_input;
  
  open (NMR_XRAY, '>NMR_Xray.csv'); {			
	$ctr_nmr_xray = 0;
	@xray =();
	@nmr =();
	print NMR_XRAY "Cluster #,NMR,XRay\n";
    for ($expmeth_line = 1; $expmeth_line < $expmethd_len; $expmeth_line++) {	
	  @pdbid_nmr_xray = split /,/,$expmethd_input[$expmeth_line];
	  if (($pdbid_nmr_xray[2]!=0) && ($pdbid_nmr_xray[3]!=0))		{# Identify pdb files generated by both NMR and X ray
		 $ctr_nmr_xray++;
		 push (@xray,$pdbid_nmr_xray[3]); push (@nmr,$pdbid_nmr_xray[2]);
		 print NMR_XRAY $ctr_nmr_xray,",",$pdbid_nmr_xray[2],",",$pdbid_nmr_xray[3];
	  }
	}
  } close (NMR_XRAY);
  $expmethd_len = $expmethd_len - 1;
  print "\nThere are $ctr_nmr_xray proteins with both NMR and X-ray structures \nout of $expmethd_len structures resolved by multiple experiments.\n";
  print "\nList of pdb files saved as \"NMR_Xray\.csv\"\n";
}